window_size: 5
train_start_date: '2020-01-01 13:30:00'
train_end_date: '2024-11-01 09:30:00'
valid_start_date: '2024-11-01 10:30:00'
valid_end_date: '2024-11-08 10:30:00'
features: Date, open, High, Low, close, volume
indicators_names: rsi macd
